import axios from 'axios'
import type { ContractAnalysis, UploadResponse } from '@/types'

const BASE_URL = import.meta.env.VITE_API_URL || ''

const api = axios.create({
  baseURL: BASE_URL,
  timeout: 120000,
})

api.interceptors.response.use(
  (response) => response,
  (error) => {
    console.error('API Error:', error.response?.data || error.message)
    return Promise.reject(error)
  }
)

export async function uploadContract(
  file: File,
  onProgress?: (pct: number) => void
): Promise<UploadResponse> {
  const formData = new FormData()
  formData.append('file', file)

  const response = await api.post<UploadResponse>('/api/upload', formData, {
    headers: { 'Content-Type': 'multipart/form-data' },
    onUploadProgress: (evt) => {
      if (evt.total && onProgress) {
        onProgress(Math.round((evt.loaded / evt.total) * 100))
      }
    },
  })
  return response.data
}

export async function analyzeContract(fileId: string): Promise<ContractAnalysis> {
  const response = await api.post<ContractAnalysis>('/api/analyze', { file_id: fileId })
  return response.data
}

export async function getAnalysis(analysisId: string): Promise<ContractAnalysis> {
  const response = await api.get<ContractAnalysis>(`/api/analysis/${analysisId}`)
  return response.data
}

export async function exportReport(analysisId: string, analysis?: import('@/types').ContractAnalysis): Promise<Blob> {
  // First try the stored analysis by ID
  try {
    const response = await api.get(`/api/export/${analysisId}`, { responseType: 'blob' })
    return response.data
  } catch {
    // Fallback: generate report client-side as text if backend lost the analysis
    if (analysis) {
      const text = buildTextReport(analysis)
      return new Blob([text], { type: 'text/plain' })
    }
    throw new Error('Export failed')
  }
}

function buildTextReport(a: import('@/types').ContractAnalysis): string {
  const rs = a.risk_summary
  const lines = [
    'LEXGUARD AI — CONTRACT ANALYSIS REPORT',
    '='.repeat(60),
    `File: ${a.filename}`,
    `Overall Risk: ${rs.overall_level} (${rs.overall_score}/100)`,
    `Contract Type: ${rs.contract_type}`,
    `Trust Score: ${rs.trust_score}%`,
    '',
    'EXECUTIVE SUMMARY',
    '-'.repeat(40),
    rs.executive_summary,
    '',
    'KEY RED FLAGS',
    '-'.repeat(40),
    ...rs.top_risks.map((r, i) => `${i + 1}. ${r}`),
    '',
    'CLAUSE-BY-CLAUSE ANALYSIS',
    '='.repeat(60),
    ...a.clauses.flatMap(c => [
      '',
      `[${c.severity}] ${c.title}`,
      `Type: ${c.type}`,
      `Original Text: ${c.raw_text.slice(0, 300)}${c.raw_text.length > 300 ? '...' : ''}`,
      `Explanation: ${c.plain_explanation}`,
      `Consequence: ${c.real_world_consequence}`,
      `Negotiation: ${c.negotiation_strategy}`,
      '-'.repeat(40),
    ]),
    '',
    'DISCLAIMER: This report is generated by AI for informational purposes only.',
    'It does not constitute legal advice. Consult a qualified attorney before signing.',
  ]
  return lines.join('\n')
}

